FROM python:3.6

{% if setup %}
RUN pip install aiohttp==2.1.0
ADD ./pydf /pydf
ADD setup.py /
RUN pip install -e .
{% endif %}

{{ example_of_var }}

LABEL maintainer 's@muelcolvin.com'

ADD ./docker-entrypoint.py /
ENTRYPOINT ["/docker-entrypoint.py"]
